---
- hosts: corespace
  become: yes
  roles:
  - network
  - xbps-repoconf
  - core-daemons
  - core-programs
  - sshd
  - apache2
  - mwh_site
  - bitlbee
  - inspircd
  - minecraft/lugCraft
  - minecraft/p0rtalCraft/lobby
  - minecraft/p0rtalCraft/survival
  - minecraft/p0rtalCraft/pillow
  - minecraft/p0rtalCraft/cakeIsSatan
  - spigot-cluster
