---
- hosts: corespace
  sudo: yes
  roles:
  - base
  - apache2
  - mwh_site
  - bitlbee
  - inspircd
  - minecraft/lugCraft
  - minecraft/p0rtalCraft/lobby
  - minecraft/p0rtalCraft/survival
  - minecraft/p0rtalCraft/pillow
  - minecraft/p0rtalCraft/cakeIsSatan
  - spigot-cluster
