---
- hosts: corespace
  sudo: yes
  roles:
  - base-shim
  # - apache2
  # - mwh_site
  # - vds_site
  - inspircd
  # - minecraft/lugCraft
  # - minecraft/p0rtalCraft/lobby
  # - minecraft/p0rtalCraft/survival
  # - minecraft/p0rtalCraft/pillow
  # - minecraft/p0rtalCraft/cakeIsSatan
  # - spigot-cluster
