---
- name: Configure firewall for apache2
  copy: src=apache2.rules dest=/etc/iptables.d/apache2.rules owner=root group=root mode=0640
  notify:
  - iptables

- name: Install packages for webserver
  apt: pkg={{ item }} state=present
  with_items:
  - mailutils
  - apache2
  - php5

- name: Enable PHP
  apache2_module: name=php5_cgi state=present

- name: Add sites-available
  copy: src=sites-available dest=/etc/apache2/ owner=root group=root mode=0644 directory_mode=0755
  notify:
  - apache2

- name: Create sites-enabled
  file: path=/etc/apache2/sites-enabled state=directory owner=root group=root mode=0755

- name: Enable sites
  file: src=../sites-available/{{ item }}.conf dest=/etc/apache2/sites-enabled/{{ item }}.conf state=link owner=root group=root
  with_items:
  - 000-default
  notify:
  - apache2

- name: Disable old default site
  file: path=/etc/apache2/sites-enabled/default state=absent
  notify:
  - apache2
