---
- name: Make iptables.d
  file: path=/etc/iptables.d state=directory owner=root group=root mode=0740

- name: Install common packages
  apt: pkg={{ item }} state=present update_cache=no
  with_items:
  - ethtool
  - ntp
  - openssh-server
  when: ansible_lsb.id == "Debian" or ansible_lsb.id == "Ubuntu"

- name: Install common packages
  xbps: name={{ item }} state=present update_cache=yes
  with_items:
  - ntp
