---
gw_network: 192.168.1.0
dhcp_self: 192.168.1.1
dhcp_lower: 192.168.1.2
dhcp_upper: 192.168.1.128

domain: temp.lug.utdallas.edu
hostname: tmp-router

int_int: bge1
ext_int: bge0

ntp:
- pool.ntp.org

staticHosts:
  temp-1:
    mac: 00:19:b9:c2:37:bd
    addr: 192.168.1.3
    name: cloud-head

stub-zones:
  UTD:
    name: utdallas.edu
    addresses:
      primary: 10.180.15.160
      secondary: 10.182.70.107
