---
gw_network: 192.168.42.0
dhcp_self: 192.168.42.1
dhcp_lower: 192.168.42.2
dhcp_upper: 192.168.42.128

domain: collegiumv.org
hostname: tmp-router

int_int: bge1
ext_int: bge0

boot_fname: pxelinux.0
boot_next: 192.168.42.7

ntp:
- pool.ntp.org

staticHosts:
  temp-1:
    mac: 00:22:19:24:7b:8a
    addr: 192.168.42.7
    name: temp-1
    CNAME:
      - www
      - preseed
  temp-2:
    mac: 00:22:19:27:e2:d5
    addr: 192.168.42.4
    name: temp-2
    CNAME:
      - ldap
  temp-3:
    mac: 00:22:19:24:7c:49
    addr: 192.168.42.5
    name: temp-3

stub-zones:
  UTD:
    name: utdallas.edu
    addresses:
      primary: 10.180.15.160
      secondary: 10.182.70.107
